services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: tododb
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
